### ISSUE TITLE
Wrong graphic?

### ISSUE THREAD

**Issue by caitsnyder** [learn-co-curriculum/dsc-common-problems-with-clustering#1]
"consider the circled points in the following plot:" --> Seems to have used the wrong image, refers to 2 points circled but it's the HAC circle visualization (all are circled)

**Comment by jessepisel** [comment]
Thanks for opening this issue @caitsnyder :wave:. This lesson has been updated with commit 3bfa1ac5d71579ef7b11032b408cffd8eddf20c1.

I am closing this issue at this time.
